root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  include_ext = ["go", "md"]
  exclude_dir = ["tmp", "web", ".git"]
  delay = 300
  stop_on_error = true
  send_interrupt = true
  kill_delay = 2000

[log]
  time = false

[misc]
  clean_on_exit = true
